# Generated by Django 3.0.1 on 2020-03-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Confirmed',
        ),
    ]
