# Generated by Django 3.0.1 on 2020-03-03 09:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200303_2015'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='confirmed',
            managers=[
                ('confirmed_cases', django.db.models.manager.Manager()),
            ],
        ),
    ]
