# Generated by Django 3.0.1 on 2020-03-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200303_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial_published',
        ),
    ]
