# Generated by Django 3.0.1 on 2020-03-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('num_cases', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
